FROM golang:1.21 as build

COPY server/ $GOPATH/src/github.com/davewalker-wk/grpc-envoy-helm
WORKDIR $GOPATH/src/github.com/davewalker-wk/grpc-envoy-helm

RUN go build -o server main.go

FROM golang:1.21

COPY --from=build $GOPATH/src/github.com/davewalker-wk/grpc-envoy-helm/server ./server

EXPOSE 8080
ENTRYPOINT ["./server"]